apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: registro-atividades
type: Opaque
stringData:
  POSTGRES_DB: registro_atividades
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: senha_secreta_aws
  DATABASE_URL: postgresql+psycopg://app_user:senha_secreta_aws@postgres-service:5432/registro_atividades
